version: '3'

services:
  web:
    image: akhmetovor/auto_repair:latest
    ports:
      - "80:8080"
    depends_on:
      - db

  db:
    image: postgres:15.0
    environment:
      POSTGRES_DB: auto_db
      POSTGRES_USER: oleg
      POSTGRES_PASSWORD: XnBX#kE9
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
