DROP TABLE aorder;
DROP TABLE appeal;
DROP TABLE car;
DROP TABLE client;

    CREATE TABLE Client (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        full_name varchar(100) NOT NULL UNIQUE
);
CREATE TABLE Car (
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     model varchar(100) NOT NULL,
                     state_number varchar(10) NOT NULL UNIQUE,
                     vin varchar(40) NOT NULL UNIQUE,
                     client_id int REFERENCES Client(id) ON DELETE SET NULL
);
CREATE TABLE Appeal (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name varchar NOT NULL,
                      fault_description varchar NOT NULL,
                      mileage int CHECK (mileage >= 0),
                      car_id int REFERENCES Car(id) ON DELETE SET NULL,
                      date_of_appeal timestamp
);
CREATE TABLE aOrder (
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar NOT NULL,
                       aValue int check (aValue >= 0),
                       order_type int,
                       appeal_id int REFERENCES Appeal(id) ON DELETE SET NULL
);
CREATE TABLE aUser (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(100) NOT NULL UNIQUE,
    password varchar NOT NULL,
    role varchar NOT NULL
);

INSERT INTO auser values ('1', '$2a$10$YNUpMu4FPOtTSNxttAHMAe9CM0zk3TGSxHhhd8Y4Zhq/L6l68omyG', 'ROLE_ADMIN');
INSERT INTO auser values ('2', '$2a$10$ECl98JnqQwpgHNlTY4s27.I1SJXkT0/wsMYHtVraQWtmO01AjMBQa', 'ROLE_USER');
INSERT INTO client values ('Ахметов Олег Рустамович');
INSERT INTO car values ('Лада Калина', 'C325EO174', '123', 1);

