CREATE TABLE Client (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        full_name varchar(100) NOT NULL UNIQUE
);
CREATE TABLE Car (
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     model varchar(100) NOT NULL,
                     state_number varchar(10) NOT NULL UNIQUE,
                     vin varchar(40) NOT NULL UNIQUE,
                     client_id int REFERENCES Client(id) ON DELETE SET NULL
);
CREATE TABLE aCase (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      mileage int CHECK (mileage >= 0),
                      car_id int REFERENCES Car(id) ON DELETE SET NULL,
                      date_of_case timestamp
);
CREATE TABLE aOrder (
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       aValue int check (aValue >= 0),
                       order_type int,
                       case_id int REFERENCES aCase(id) ON DELETE SET NULL
);
CREATE TABLE aUser (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(100) NOT NULL UNIQUE,
    password varchar NOT NULL,
    role varchar NOT NULL
);
