CREATE TABLE Car (
                     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     model varchar(100) NOT NULL,
                     state_number varchar(10) NOT NULL UNIQUE,
                     vin varchar(40) NOT NULL UNIQUE,
                     client_id int REFERENCES Client(id) ON DELETE SET NULL,
                     filename varchar
);