CREATE TABLE Appeal (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name varchar NOT NULL,
                      fault_description varchar,
                      mileage int CHECK (mileage >= 0),
                      car_id bigint REFERENCES Car(id) ON DELETE SET NULL,
                      date_of_appeal timestamp
);