CREATE TABLE aOrder (
                       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar NOT NULL,
                       aValue int check (aValue >= 0),
                       order_type int,
                       appeal_id bigint REFERENCES Appeal(id) ON DELETE SET NULL
);